---

name: Release Packages

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version (i.e. v0.22.3-pre.2)'
        required: true

jobs:
  release-envoy-docker-image:
    name: Release Envoy to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU to run multi-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Get tag
        uses: actions/github-script@v6
        id: tag
        with:
          result-encoding: string
          script: "return context.eventName === 'workflow_dispatch' ? core.getInput('tag') : context.payload.release.tag_name;"

      - name: Set suffix
        uses: actions/github-script@v6
        id: suffix
        with:
          result-encoding: string
          script: |
            const fullTag = '${{steps.tag.outputs.result}}';
            if (fullTag.includes('-')) {
              const [, fullSuffix] = fullTag.split('-');
              const [suffix] = fullSuffix.split('.');
              return `-${suffix}`;
            } else {
              return '';
            }

      - name: Set Docker tags and labels
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: dashpay/envoy
          tags: |
            type=match,pattern=v(\d+),group=1,value=${{steps.tag.outputs.result}}
            type=match,pattern=v(\d+.\d+),group=1,value=${{steps.tag.outputs.result}}
            type=match,pattern=v(\d+.\d+.\d+),group=1,value=${{steps.tag.outputs.result}}
            type=match,pattern=v(.*),group=1,value=${{steps.tag.outputs.result}},suffix=
          flavor: |
            suffix=${{ steps.suffix.outputs.result }},onlatest=true
            latest=${{ github.event_name == 'release' }}

      - name: Build and push Docker image for Envoy
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
